// sifra.cpp : Defines the entry point for the console application.
//

#include "stdafx.h"
#include <stdio.h>
#include "bigrams.h"
#include <stdlib.h>

char sifra[531] = 
"HMGPYGEXVXOBYOKUKFUFXILTBPKIYKNIGCUKCKOHLFBPUNGJFKHPJEXHLHXPBFNKFGYOKUKFXVKOBINKVKOGHKOZKUPXSJIKYIXHIMOKKCKRBOKUGTBMGKYGEFBVRLOGNKYPKNGCXFGMOXCKHBNBOKUGIKOUKCXPXYIGFGNXVKYBFKYGEFBVHPBVRLOKYGOBTXKNKNBRLOKZXENKOKMXHUGIKOULHXEOXEIJMXUKCEKZBNKKMOKHNXIJVYOKUKFPFKIBVCXCOGJFOKOXUGIKOULRLOLEXNNXTXIPFHXRLOGMGENXVJCPULTMUFXIBCHXEKOBOGUXFUELCHTMIPFOBEGPXRXYKNKUKKOXVKOGUEGFGJVXOFKURIKHJINXZKUGTJYXIKFXETGVJPZXNBUXVGFINJOGPXEKOYGEFBVYOKUKFXVTBVEKOFBVTKPFXZBKTBVTKPFXZBFBVEXOXNXFIHKOGEOGJMGKYBOZKUGFXNUIKFNXCYGFUKOTMKPNBUKHCKYIKPXNXVSIKTUJQQ";


int main(int argc, char* argv[])
{
	int i;
	BIGRAM *big;
	int pocet;
	printf("SIFRA: %s\n\n", sifra);
	bigrams(sifra, &big, &pocet);

	for(i=0; i<pocet; i++)
	{
		printf("BG: %s - %d, %f\n",big[i].bigram, big[i].vyskyt, big[i].fr);
	}
	free(big);

	return 0;
}
