22. 1. 10:52
Microsoft predstavil Windows Data Session Toolkit, coz je jeho implementace DRM. WDST ma zajistit ochranu datovych medii proti kopirovani tim, ze vytvari na mediu vedle chranene stopy jeste druhou stopu, kodovanou ve WMA, ktera jde prehrat na PC. Komentar TheRegisteru.
 [Radoomek]

22. 1. 11:11
Na The Spam Conference, ktera se uskutecnila na Massachusetts Institute of Technology, byla siroce diskutovana SPAMova situace na Internetu. Misto ocekavanych triceti recniku se prihlasilo pres 500 diskuteru. Byl take predstaven model statistickeho filtru na SPAM, ktery dnesni SPAMeri zatim prilis casto neprekonavaji a dana k verejnemu uzivani databaze pro trenovani statistickych filtru. [Radoomek]

22. 1. 10:52
Microsoft predstavil Windows Data Session Toolkit, coz je jeho implementace DRM. WDST ma zajistit ochranu datovych medii proti kopirovani tim, ze vytvari na mediu vedle chranene stopy jeste druhou stopu, kodovanou ve WMA, ktera jde prehrat na PC. Komentar TheRegisteru.
 [Radoomek]

22. 1. 11:11
Na The Spam Conference, ktera se uskutecnila na Massachusetts Institute of Technology, byla siroce diskutovana SPAMova situace na Internetu. Misto ocekavanych triceti recniku se prihlasilo pres 500 diskuteru. Byl take predstaven model statistickeho filtru na SPAM, ktery dnesni SPAMeri zatim prilis casto neprekonavaji a dana k verejnemu uzivani databaze pro trenovani statistickych filtru. [Radoomek]

22. 1. 11:11
Na The Spam Conference, ktera se uskutecnila na Massachusetts Institute of Technology, byla siroce diskutovana SPAMova situace na Internetu. Misto ocekavanych triceti recniku se prihlasilo pres 500 diskuteru. Byl take predstaven model statistickeho filtru na SPAM, ktery dnesni SPAMeri zatim prilis casto neprekonavaji a dana k verejnemu uzivani databaze pro trenovani statistickych filtru. [Radoomek]

